// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: MiniRPGComm.proto

package MiniRPGComm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MiniRPGComm_GetIntroduction_FullMethodName = "/MiniRPGComm/GetIntroduction"
	MiniRPGComm_SetInput_FullMethodName        = "/MiniRPGComm/SetInput"
)

// MiniRPGCommClient is the client API for MiniRPGComm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MiniRPGCommClient interface {
	GetIntroduction(ctx context.Context, in *IntroductionRequest, opts ...grpc.CallOption) (*IntroductionResponse, error)
	SetInput(ctx context.Context, in *Input, opts ...grpc.CallOption) (*PlayerState, error)
}

type miniRPGCommClient struct {
	cc grpc.ClientConnInterface
}

func NewMiniRPGCommClient(cc grpc.ClientConnInterface) MiniRPGCommClient {
	return &miniRPGCommClient{cc}
}

func (c *miniRPGCommClient) GetIntroduction(ctx context.Context, in *IntroductionRequest, opts ...grpc.CallOption) (*IntroductionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntroductionResponse)
	err := c.cc.Invoke(ctx, MiniRPGComm_GetIntroduction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniRPGCommClient) SetInput(ctx context.Context, in *Input, opts ...grpc.CallOption) (*PlayerState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerState)
	err := c.cc.Invoke(ctx, MiniRPGComm_SetInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiniRPGCommServer is the server API for MiniRPGComm service.
// All implementations should embed UnimplementedMiniRPGCommServer
// for forward compatibility.
type MiniRPGCommServer interface {
	GetIntroduction(context.Context, *IntroductionRequest) (*IntroductionResponse, error)
	SetInput(context.Context, *Input) (*PlayerState, error)
}

// UnimplementedMiniRPGCommServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiniRPGCommServer struct{}

func (UnimplementedMiniRPGCommServer) GetIntroduction(context.Context, *IntroductionRequest) (*IntroductionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntroduction not implemented")
}
func (UnimplementedMiniRPGCommServer) SetInput(context.Context, *Input) (*PlayerState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInput not implemented")
}
func (UnimplementedMiniRPGCommServer) testEmbeddedByValue() {}

// UnsafeMiniRPGCommServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiniRPGCommServer will
// result in compilation errors.
type UnsafeMiniRPGCommServer interface {
	mustEmbedUnimplementedMiniRPGCommServer()
}

func RegisterMiniRPGCommServer(s grpc.ServiceRegistrar, srv MiniRPGCommServer) {
	// If the following call pancis, it indicates UnimplementedMiniRPGCommServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MiniRPGComm_ServiceDesc, srv)
}

func _MiniRPGComm_GetIntroduction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntroductionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniRPGCommServer).GetIntroduction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniRPGComm_GetIntroduction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniRPGCommServer).GetIntroduction(ctx, req.(*IntroductionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniRPGComm_SetInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniRPGCommServer).SetInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniRPGComm_SetInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniRPGCommServer).SetInput(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

// MiniRPGComm_ServiceDesc is the grpc.ServiceDesc for MiniRPGComm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiniRPGComm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MiniRPGComm",
	HandlerType: (*MiniRPGCommServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIntroduction",
			Handler:    _MiniRPGComm_GetIntroduction_Handler,
		},
		{
			MethodName: "SetInput",
			Handler:    _MiniRPGComm_SetInput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "MiniRPGComm.proto",
}
