// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.1
// source: MiniRPGComm.proto

package MiniRPGComm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntroductionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Passcode *string `protobuf:"bytes,2,req,name=passcode" json:"passcode,omitempty"`
}

func (x *IntroductionRequest) Reset() {
	*x = IntroductionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MiniRPGComm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntroductionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntroductionRequest) ProtoMessage() {}

func (x *IntroductionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MiniRPGComm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntroductionRequest.ProtoReflect.Descriptor instead.
func (*IntroductionRequest) Descriptor() ([]byte, []int) {
	return file_MiniRPGComm_proto_rawDescGZIP(), []int{0}
}

func (x *IntroductionRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *IntroductionRequest) GetPasscode() string {
	if x != nil && x.Passcode != nil {
		return *x.Passcode
	}
	return ""
}

type IntroductionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Message  *string `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
}

func (x *IntroductionResponse) Reset() {
	*x = IntroductionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MiniRPGComm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntroductionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntroductionResponse) ProtoMessage() {}

func (x *IntroductionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MiniRPGComm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntroductionResponse.ProtoReflect.Descriptor instead.
func (*IntroductionResponse) Descriptor() ([]byte, []int) {
	return file_MiniRPGComm_proto_rawDescGZIP(), []int{1}
}

func (x *IntroductionResponse) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *IntroductionResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *int32 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MiniRPGComm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_MiniRPGComm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_MiniRPGComm_proto_rawDescGZIP(), []int{2}
}

func (x *Input) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type PlayerState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *int64 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y *int64 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MiniRPGComm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_MiniRPGComm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_MiniRPGComm_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerState) GetX() int64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *PlayerState) GetY() int64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

var File_MiniRPGComm_proto protoreflect.FileDescriptor

var file_MiniRPGComm_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4d, 0x69, 0x6e, 0x69, 0x52, 0x50, 0x47, 0x43, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x13, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x63, 0x6f,
	0x64, 0x65, 0x22, 0x4c, 0x0a, 0x14, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x1d, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x29, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x01, 0x79, 0x32, 0x73, 0x0a, 0x0b, 0x4d, 0x69,
	0x6e, 0x69, 0x52, 0x50, 0x47, 0x43, 0x6f, 0x6d, 0x6d, 0x12, 0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x2e, 0x69,
	0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x08, 0x53,
	0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x06, 0x2e, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x0c, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x42,
	0x2e, 0x5a, 0x2c, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62,
	0x6d, 0x61, 0x64, 0x65, 0x72, 0x32, 0x33, 0x2f, 0x4d, 0x69, 0x6e, 0x69, 0x52, 0x50, 0x47, 0x52,
	0x50, 0x43, 0x2f, 0x4d, 0x69, 0x6e, 0x69, 0x52, 0x50, 0x47, 0x43, 0x6f, 0x6d, 0x6d, 0x3b,
}

var (
	file_MiniRPGComm_proto_rawDescOnce sync.Once
	file_MiniRPGComm_proto_rawDescData = file_MiniRPGComm_proto_rawDesc
)

func file_MiniRPGComm_proto_rawDescGZIP() []byte {
	file_MiniRPGComm_proto_rawDescOnce.Do(func() {
		file_MiniRPGComm_proto_rawDescData = protoimpl.X.CompressGZIP(file_MiniRPGComm_proto_rawDescData)
	})
	return file_MiniRPGComm_proto_rawDescData
}

var file_MiniRPGComm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_MiniRPGComm_proto_goTypes = []any{
	(*IntroductionRequest)(nil),  // 0: introductionRequest
	(*IntroductionResponse)(nil), // 1: introductionResponse
	(*Input)(nil),                // 2: input
	(*PlayerState)(nil),          // 3: playerState
}
var file_MiniRPGComm_proto_depIdxs = []int32{
	0, // 0: MiniRPGComm.GetIntroduction:input_type -> introductionRequest
	2, // 1: MiniRPGComm.SetInput:input_type -> input
	1, // 2: MiniRPGComm.GetIntroduction:output_type -> introductionResponse
	3, // 3: MiniRPGComm.SetInput:output_type -> playerState
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MiniRPGComm_proto_init() }
func file_MiniRPGComm_proto_init() {
	if File_MiniRPGComm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MiniRPGComm_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IntroductionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MiniRPGComm_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IntroductionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MiniRPGComm_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MiniRPGComm_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PlayerState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MiniRPGComm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_MiniRPGComm_proto_goTypes,
		DependencyIndexes: file_MiniRPGComm_proto_depIdxs,
		MessageInfos:      file_MiniRPGComm_proto_msgTypes,
	}.Build()
	File_MiniRPGComm_proto = out.File
	file_MiniRPGComm_proto_rawDesc = nil
	file_MiniRPGComm_proto_goTypes = nil
	file_MiniRPGComm_proto_depIdxs = nil
}
