// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: Admin/Introduction.proto

package Introduction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Introduction_GetIntroduction_FullMethodName = "/Introduction/GetIntroduction"
)

// IntroductionClient is the client API for Introduction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntroductionClient interface {
	GetIntroduction(ctx context.Context, in *IntroductionRequest, opts ...grpc.CallOption) (*IntroductionResponse, error)
}

type introductionClient struct {
	cc grpc.ClientConnInterface
}

func NewIntroductionClient(cc grpc.ClientConnInterface) IntroductionClient {
	return &introductionClient{cc}
}

func (c *introductionClient) GetIntroduction(ctx context.Context, in *IntroductionRequest, opts ...grpc.CallOption) (*IntroductionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntroductionResponse)
	err := c.cc.Invoke(ctx, Introduction_GetIntroduction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntroductionServer is the server API for Introduction service.
// All implementations should embed UnimplementedIntroductionServer
// for forward compatibility.
type IntroductionServer interface {
	GetIntroduction(context.Context, *IntroductionRequest) (*IntroductionResponse, error)
}

// UnimplementedIntroductionServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntroductionServer struct{}

func (UnimplementedIntroductionServer) GetIntroduction(context.Context, *IntroductionRequest) (*IntroductionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntroduction not implemented")
}
func (UnimplementedIntroductionServer) testEmbeddedByValue() {}

// UnsafeIntroductionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntroductionServer will
// result in compilation errors.
type UnsafeIntroductionServer interface {
	mustEmbedUnimplementedIntroductionServer()
}

func RegisterIntroductionServer(s grpc.ServiceRegistrar, srv IntroductionServer) {
	// If the following call pancis, it indicates UnimplementedIntroductionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Introduction_ServiceDesc, srv)
}

func _Introduction_GetIntroduction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntroductionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntroductionServer).GetIntroduction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Introduction_GetIntroduction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntroductionServer).GetIntroduction(ctx, req.(*IntroductionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Introduction_ServiceDesc is the grpc.ServiceDesc for Introduction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Introduction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Introduction",
	HandlerType: (*IntroductionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIntroduction",
			Handler:    _Introduction_GetIntroduction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Admin/Introduction.proto",
}
